name: Symfony App

on:
    push:
        branches:
            - master
            - develop
    pull_request:
        branches:
            - master
            - develop
    release:
        types: [published]

jobs:

    build:

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v1
            - name: Build the docker images
              run: make build-test
            - name: Start the docker images
              run: make start-test
            - name: Check running containers
              run: docker ps -a
            - name: Run migrations
              run: make drop-migrate
            - name: Setup transports for Messenger component
              run: make messenger-setup-transports
            - name: Run test suite
              run: make phpunit
            - name: Run PHP coding standard
              run: make ecs
            - name: Run PHP codeSniffer
              run: make phpcs
            - name: Run PHP copy/paste detector
              run: make phpcpd
            - name: Run PHP mess detector
              run: make phpmd
            - name: Run PHPStan static analysis tool
              run: make phpstan
            - name: Run Phpinsights PHP quality checks
              run: make phpinsights
            - name: Stop the docker images
              run: make stop-test
